import { z } from "zod";
import { prisma } from "../db/prisma";
import { AppError } from "../errors/app-error";
import type { AuthenticatedActor } from "../permissions/actor";
import { requireRole } from "../permissions/actor";
import { requireTeacherGroupAccess } from "./ownership.service";
import { writeAuditLog } from "./audit.service";

const uuid=z.string().uuid(),text=z.string().trim().min(1).max(5000);

export async function updateLesson(raw:unknown,actor:AuthenticatedActor|null){const trusted=requireRole(actor,["ADMIN","TEACHER"]),input=z.object({lessonId:uuid,title:text.optional(),summary:text.nullable().optional(),studiedContent:text.nullable().optional(),grammar:text.nullable().optional(),parentComment:text.nullable().optional(),internalTeacherComment:text.nullable().optional(),status:z.enum(["DRAFT","COMPLETED","CANCELLED"]).optional()}).parse(raw);return prisma.$transaction(async tx=>{const lesson=await tx.lesson.findFirst({where:{id:input.lessonId,archivedAt:null},select:{id:true,groupId:true,status:true}});if(!lesson)throw new AppError("NOT_FOUND","Урок не найден",404);await requireTeacherGroupAccess(tx,trusted,lesson.groupId);const {lessonId,...data}=input;const saved=await tx.lesson.update({where:{id:lessonId},data,select:{id:true,title:true,status:true,updatedAt:true}});await writeAuditLog(tx,{actorUserId:trusted.userId,action:"UPDATE",entityType:"Lesson",entityId:lessonId,previousData:lesson,newData:saved});return saved;});}
export async function archiveLesson(raw:unknown,actor:AuthenticatedActor|null){const trusted=requireRole(actor,["ADMIN","TEACHER"]),{lessonId}=z.object({lessonId:uuid}).parse(raw);return prisma.$transaction(async tx=>{const lesson=await tx.lesson.findFirst({where:{id:lessonId,archivedAt:null},select:{id:true,groupId:true}});if(!lesson)throw new AppError("NOT_FOUND","Урок не найден",404);await requireTeacherGroupAccess(tx,trusted,lesson.groupId);const saved=await tx.lesson.update({where:{id:lessonId},data:{archivedAt:new Date()},select:{id:true,archivedAt:true}});await writeAuditLog(tx,{actorUserId:trusted.userId,action:"ARCHIVE",entityType:"Lesson",entityId:lessonId,newData:saved});return saved;});}

export async function saveHomeworkStatus(raw:unknown,actor:AuthenticatedActor|null){const trusted=requireRole(actor,["ADMIN","TEACHER"]),input=z.object({homeworkId:uuid,studentId:uuid,status:z.enum(["ASSIGNED","COMPLETED","PARTIALLY_COMPLETED","NOT_COMPLETED","CHECKED"]),teacherComment:z.string().trim().max(2000).nullable().optional()}).parse(raw);return prisma.$transaction(async tx=>{const homework=await tx.homework.findFirst({where:{id:input.homeworkId,archivedAt:null},select:{id:true,groupId:true}});if(!homework)throw new AppError("NOT_FOUND","Задание не найдено",404);await requireTeacherGroupAccess(tx,trusted,homework.groupId);const enrolled=await tx.studentGroupEnrollment.findFirst({where:{studentId:input.studentId,groupId:homework.groupId},select:{id:true}});if(!enrolled)throw new AppError("NOT_FOUND","Ученик не найден",404);const saved=await tx.studentHomeworkStatus.upsert({where:{homeworkId_studentId:{homeworkId:input.homeworkId,studentId:input.studentId}},create:{...input,checkedById:trusted.userId,checkedAt:input.status==="CHECKED"?new Date():null},update:{status:input.status,teacherComment:input.teacherComment,checkedById:trusted.userId,checkedAt:input.status==="CHECKED"?new Date():null},select:{id:true,status:true,updatedAt:true}});await writeAuditLog(tx,{actorUserId:trusted.userId,action:"UPDATE",entityType:"StudentHomeworkStatus",entityId:saved.id,newData:saved});return saved;});}

export async function createVocabularyWords(raw:unknown,actor:AuthenticatedActor|null){const trusted=requireRole(actor,["ADMIN","TEACHER"]),input=z.object({groupId:uuid,topicId:uuid,lessonId:uuid.nullable().optional(),learnedAt:z.coerce.date().nullable().optional(),words:z.array(z.object({english:text,translation:text,example:z.string().trim().max(1000).nullable().optional()})).min(1).max(100)}).parse(raw);return prisma.$transaction(async tx=>{await requireTeacherGroupAccess(tx,trusted,input.groupId);const group=await tx.group.findFirst({where:{id:input.groupId,archivedAt:null},select:{bookId:true,enrollments:{where:{status:"ACTIVE",endedAt:null},select:{studentId:true}}}}),topic=await tx.topic.findFirst({where:{id:input.topicId,archivedAt:null,unit:{bookId:group?.bookId}},select:{id:true}});if(!group||!topic)throw new AppError("BUSINESS_RULE_VIOLATION","Тема не относится к учебнику группы",409);const created=[];for(const word of input.words){const saved=await tx.vocabularyWord.upsert({where:{topicId_english:{topicId:input.topicId,english:word.english}},create:{...word,topicId:input.topicId,lessonId:input.lessonId,learnedAt:input.learnedAt,createdById:trusted.userId},update:{translation:word.translation,example:word.example,learnedAt:input.learnedAt,archivedAt:null},select:{id:true,english:true}});created.push(saved);if(group.enrollments.length)await tx.studentWordProgress.createMany({data:group.enrollments.map(({studentId})=>({studentId,wordId:saved.id})),skipDuplicates:true});}await writeAuditLog(tx,{actorUserId:trusted.userId,action:"CREATE",entityType:"VocabularyWordBatch",entityId:input.topicId,newData:{count:created.length}});return created;});}
export async function updateVocabularyWord(raw:unknown,actor:AuthenticatedActor|null){const trusted=requireRole(actor,["ADMIN","TEACHER"]),input=z.object({wordId:uuid,english:text.optional(),translation:text.optional(),example:z.string().trim().max(1000).nullable().optional(),learnedAt:z.coerce.date().nullable().optional()}).parse(raw);return prisma.$transaction(async tx=>{const word=await tx.vocabularyWord.findFirst({where:{id:input.wordId,archivedAt:null},select:{id:true,lesson:{select:{groupId:true}},createdById:true}});if(!word)throw new AppError("NOT_FOUND","Слово не найдено",404);if(word.lesson)await requireTeacherGroupAccess(tx,trusted,word.lesson.groupId);else if(trusted.role==="TEACHER"&&word.createdById!==trusted.userId)throw new AppError("NOT_FOUND","Слово не найдено",404);const {wordId,...data}=input;return tx.vocabularyWord.update({where:{id:wordId},data,select:{id:true,english:true,translation:true}});});}
export async function archiveVocabularyWord(raw:unknown,actor:AuthenticatedActor|null){const trusted=requireRole(actor,["ADMIN","TEACHER"]),{wordId}=z.object({wordId:uuid}).parse(raw);return prisma.$transaction(async tx=>{const word=await tx.vocabularyWord.findFirst({where:{id:wordId,archivedAt:null},select:{id:true,lesson:{select:{groupId:true}},createdById:true}});if(!word)throw new AppError("NOT_FOUND","Слово не найдено",404);if(word.lesson)await requireTeacherGroupAccess(tx,trusted,word.lesson.groupId);else if(trusted.role==="TEACHER"&&word.createdById!==trusted.userId)throw new AppError("NOT_FOUND","Слово не найдено",404);return tx.vocabularyWord.update({where:{id:wordId},data:{archivedAt:new Date()},select:{id:true,archivedAt:true}});});}
export async function saveWordProgress(raw:unknown,actor:AuthenticatedActor|null){const trusted=requireRole(actor,["ADMIN","TEACHER"]),input=z.object({studentId:uuid,wordId:uuid,status:z.enum(["NEW","LEARNING","NEEDS_REVIEW","MASTERED","CONFIDENT"]),teacherComment:z.string().trim().max(2000).nullable().optional()}).parse(raw);return prisma.$transaction(async tx=>{const enrollment=await tx.studentGroupEnrollment.findFirst({where:{studentId:input.studentId,status:"ACTIVE",endedAt:null,group:{teacherAssignments:{some:{teacherId:trusted.userId,isCurrent:true,endedAt:null}}}},select:{id:true}});if(trusted.role==="TEACHER"&&!enrollment)throw new AppError("NOT_FOUND","Ученик не найден",404);return tx.studentWordProgress.upsert({where:{studentId_wordId:{studentId:input.studentId,wordId:input.wordId}},create:{...input,assessedById:trusted.userId,assessedAt:new Date()},update:{status:input.status,teacherComment:input.teacherComment,assessedById:trusted.userId,assessedAt:new Date()},select:{id:true,status:true}});});}

export async function updateOwnProfile(raw:unknown,actor:AuthenticatedActor|null){const trusted=requireRole(actor,["TEACHER","PARENT"]),input=z.object({firstName:z.string().trim().min(1).max(100),lastName:z.string().trim().min(1).max(100),phone:z.string().trim().min(7).max(24).nullable().optional()}).parse(raw);return prisma.$transaction(async tx=>{const previous=await tx.user.findUnique({where:{id:trusted.userId},select:{firstName:true,lastName:true,phone:true}});const saved=await tx.user.update({where:{id:trusted.userId},data:input,select:{id:true,firstName:true,lastName:true,phone:true}});await writeAuditLog(tx,{actorUserId:trusted.userId,action:"UPDATE",entityType:"UserProfile",entityId:trusted.userId,previousData:previous,newData:saved});return saved;});}
