import { z } from "zod";

const id = z.string().uuid();
const nonEmpty = z.string().trim().min(1).max(300);
const date = z.coerce.date();
const optionalText = z.string().trim().max(5000).optional().nullable();
export const iinSchema = z.string().trim().regex(/^\d{12}$/, "ИИН должен содержать ровно 12 цифр");

export const createUserSchema = z.object({ iin:iinSchema, email: z.string().trim().toLowerCase().email().optional().nullable(), phone: z.string().trim().min(7).max(24).optional().nullable(), firstName: nonEmpty, lastName: nonEmpty, middleName: z.string().trim().max(100).optional().nullable(), role: z.enum(["ADMIN","TEACHER","PARENT"]), password:z.string().min(10,"Пароль должен содержать минимум 10 символов").max(200) }).superRefine((value,context)=>{if(value.role==="ADMIN"&&!value.email)context.addIssue({code:"custom",path:["email"],message:"Email обязателен для администратора"})});
export const updateUserSchema = z.object({ iin:iinSchema.optional(), email:z.string().trim().toLowerCase().email().nullable().optional(), phone:z.string().trim().min(7).max(24).nullable().optional(), firstName:nonEmpty.optional(), lastName:nonEmpty.optional(), middleName:z.string().trim().max(100).nullable().optional(), status:z.enum(["ACTIVE","INACTIVE"]).optional(), password:z.string().min(10,"Пароль должен содержать минимум 10 символов").max(200).optional() }).refine(value=>Object.keys(value).length>0,{message:"Нет изменений"});
export const createStudentSchema = z.object({ firstName: nonEmpty, lastName: nonEmpty, middleName: z.string().trim().max(100).optional().nullable(), dateOfBirth: date.optional().nullable(), startedAt: date.default(()=>new Date()), currentLevel: z.string().trim().max(80).optional().nullable(), note: optionalText }).refine(v=>!v.dateOfBirth||v.dateOfBirth<=new Date(),{message:"Дата рождения не может быть в будущем",path:["dateOfBirth"]});
export const updateStudentSchema = z.object({ firstName:nonEmpty.optional(), lastName:nonEmpty.optional(), middleName:z.string().trim().max(100).nullable().optional(), dateOfBirth:date.nullable().optional(), currentLevel:z.string().trim().max(80).nullable().optional(), note:optionalText, status:z.enum(["ACTIVE","PAUSED","COMPLETED","INACTIVE","GRADUATED"]).optional() }).refine(value=>Object.keys(value).length>0,{message:"Нет изменений"});
export const linkParentSchema = z.object({ parentId:id, studentId:id, relationType:z.enum(["MOTHER","FATHER","GUARDIAN","OTHER"]), isPrimary:z.boolean().default(false) });
export const createGroupSchema = z.object({ name:nonEmpty, level:nonEmpty, courseId:id, bookId:id, academicPeriodId:id, capacity:z.number().int().positive().max(100), startDate:date, endDate:date.optional().nullable(), note:optionalText }).refine(v=>!v.endDate||v.endDate>=v.startDate,{message:"Дата окончания раньше даты начала",path:["endDate"]});
export const updateGroupSchema = z.object({ name:nonEmpty.optional(), level:nonEmpty.optional(), capacity:z.number().int().positive().max(100).optional(), endDate:date.nullable().optional(), note:optionalText, status:z.enum(["RECRUITING","ACTIVE","COMPLETED"]).optional() }).refine(value=>Object.keys(value).length>0,{message:"Нет изменений"});
export const transferStudentSchema = z.object({ studentId:id, targetGroupId:id, transferDate:date, reason:z.string().trim().min(3).max(1000) });
export const createLessonSchema = z.object({ groupId:id, bookId:id, unitId:id, topicId:id, teacherId:id, academicPeriodId:id, lessonDate:date, lessonType:z.enum(["REGULAR","REVIEW","TEST","SPEAKING_PRACTICE","FINAL"]).default("REGULAR"), title:nonEmpty, summary:optionalText, studiedContent:optionalText, grammar:optionalText, parentComment:optionalText, internalTeacherComment:optionalText });
export const attendanceEntrySchema = z.object({ studentId:id, status:z.enum(["PRESENT","ABSENT","LATE","EXCUSED","LESSON_CANCELLED"]), comment:z.string().trim().max(1000).optional().nullable() });
export const saveAttendanceSchema = z.object({ lessonId:id, entries:z.array(attendanceEntrySchema).min(1).max(100) });
export const homeworkSchema = z.object({ lessonId:id.optional().nullable(), groupId:id, title:nonEmpty, bookId:id.optional().nullable(), bookName:z.string().trim().max(200).optional().nullable(), page:z.string().trim().max(50).optional().nullable(), exercises:z.string().trim().max(200).optional().nullable(), description:z.string().trim().min(1).max(5000), dueDate:date.optional().nullable(), attachmentUrl:z.string().url().optional().nullable() });
export const updateHomeworkSchema = homeworkSchema.omit({groupId:true}).partial().refine(value=>Object.keys(value).length>0,{message:"Нет изменений"});
export const testSchema = z.object({ groupId:id, unitId:id, title:nonEmpty, testDate:date, maxScore:z.number().positive().max(10000) });
export const updateTestSchema = testSchema.omit({groupId:true,unitId:true}).partial().extend({status:z.enum(["DRAFT","ACTIVE","COMPLETED"]).optional()}).refine(value=>Object.keys(value).length>0,{message:"Нет изменений"});
export const testResultSchema = z.object({ testId:id, studentId:id, score:z.number().min(0), maxScore:z.number().positive(), teacherComment:optionalText }).refine(v=>v.score<=v.maxScore,{message:"Баллы превышают максимум",path:["score"]});
export const monthlyAssessmentSchema = z.object({ studentId:id, groupId:id, teacherId:id, academicPeriodId:id, year:z.number().int().min(2020).max(2100), month:z.number().int().min(1).max(12), scores:z.array(z.object({skillCategoryId:id,score:z.number().int().min(1).max(10),teacherComment:optionalText})).min(1) });
export const teacherReviewSchema = z.object({ studentId:id, groupId:id, teacherId:id, academicPeriodId:id, year:z.number().int().min(2020).max(2100), month:z.number().int().min(1).max(12), achievements:optionalText, improvements:optionalText, recommendations:optionalText, generalComment:optionalText, progressLevel:z.enum(["SIGNIFICANT","STABLE","SMALL","NO_VISIBLE_CHANGE","NEEDS_ATTENTION"]) }).refine(v=>Boolean(v.achievements||v.improvements||v.recommendations||v.generalComment),{message:"Отзыв не может быть пустым"});
export const academicPeriodSchema = z.object({ name:nonEmpty, type:z.enum(["ACADEMIC_YEAR","SEMESTER","TERM","SUMMER","CUSTOM"]), startDate:date, endDate:date, status:z.enum(["PLANNED","CURRENT","COMPLETED","ARCHIVED"]).default("PLANNED"), isCurrent:z.boolean().default(false) }).refine(v=>v.endDate>=v.startDate,{message:"Дата окончания раньше даты начала",path:["endDate"]});

export type TransferStudentInput = z.infer<typeof transferStudentSchema>;
