"use client";

import Link from "next/link";
import { useState } from "react";
import { AlertTriangle, Archive, ArrowLeftRight, BarChart3, BookOpen, CalendarDays, Check, ChevronRight, ClipboardList, Edit3, Eye, GraduationCap, History, Layers3, Plus, RefreshCw, Search, ShieldCheck, Sparkles, UserRound, UsersRound, X } from "lucide-react";
import type { LucideIcon } from "lucide-react";
import { academicPeriods, adminGroups as initialGroups, adminParents as initialParents, adminStudents as initialStudents, adminTeachers as initialTeachers, adminUser, archivedEntities as initialArchived, auditLog, books, courses, learningHistory as initialHistory, skillCategories, topics, units } from "../lib/admin-data";
import type { AdminGroup, AdminStudent, ArchivedEntity, Parent, Teacher } from "../lib/types";

type Toast = { text: string; tone?: "success" | "danger" } | null;
type PersonEntity = Teacher | Parent | AdminStudent;
type EntityKind = "teachers" | "parents" | "students";
const labels = { teachers: "учителя", parents: "родителя", students: "ученика" };

function Badge({ status }: { status: string }) {
  const map: Record<string,[string,string]> = { active:["Активен","green"], inactive:["Неактивен","gray"], archived:["В архиве","gray"], draft:["Черновик","orange"], upcoming:["Предстоящий","blue"] };
  const [label,tone]=map[status]??[status,"blue"];
  return <span className={`badge ${tone}`}>{label}</span>;
}

function Modal({ title, children, onClose, wide=false }: { title: string; children: React.ReactNode; onClose:()=>void; wide?:boolean }) {
  return <div className="admin-modal-layer" onMouseDown={(event)=>event.target===event.currentTarget&&onClose()}><section className={`admin-modal ${wide?"wide":""}`} role="dialog" aria-modal="true" aria-label={title}><header><div><span>Happy Town · ADMIN</span><h2>{title}</h2></div><button onClick={onClose} aria-label="Закрыть"><X size={20}/></button></header>{children}</section></div>;
}

function Confirm({ title, text, confirm="Подтвердить", danger=false, onClose, onConfirm }: { title:string;text:string;confirm?:string;danger?:boolean;onClose:()=>void;onConfirm:()=>void }) {
  return <Modal title={title} onClose={onClose}><div className="confirm-copy"><span className={danger?"danger":""}><AlertTriangle/></span><p>{text}</p></div><div className="admin-form-actions"><button className="btn secondary" onClick={onClose}>Отмена</button><button className={`btn ${danger?"danger-btn":""}`} onClick={onConfirm}>{confirm}</button></div></Modal>;
}

function Toolbar({ query, setQuery, action, filters=true }: { query:string;setQuery:(v:string)=>void;action?:React.ReactNode;filters?:boolean }) {
  return <div className="admin-toolbar"><label className="admin-search"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Поиск по имени или данным" aria-label="Поиск"/></label>{filters&&<><select aria-label="Статус"><option>Все статусы</option><option>Активные</option><option>Неактивные</option></select><select aria-label="Сортировка"><option>Сначала новые</option><option>По алфавиту</option></select></>}{action}</div>;
}

function Dashboard({ students, teachers, parents, groups, openCreate }: { students:AdminStudent[];teachers:Teacher[];parents:Parent[];groups:AdminGroup[];openCreate:(kind:EntityKind)=>void }) {
  const attendance=[72,78,81,79,84,87]; const lessons=[34,38,42,47,53,58];
  const stats: Array<[LucideIcon,string,string|number,string]> = [[GraduationCap,"Активные ученики",students.filter(s=>s.status==="active").length,"+4 за месяц"],[UserRound,"Активные учителя",teachers.filter(t=>t.status==="active").length,"4 специалиста"],[UsersRound,"Родители",parents.length,"14 связаны с детьми"],[Layers3,"Группы",groups.length,"1 требует внимания"],[BookOpen,"Текущие курсы",courses.filter(c=>c.status==="active").length,"4 программы"],[Archive,"В архиве",initialArchived.length,"3 типа записей"],[CalendarDays,"Занятия за месяц",58,"+5 к июню"],[BarChart3,"Посещаемость","87%","+3% к июню"]];
  const quickActions: Array<[string,()=>void,LucideIcon]> = [["Добавить ученика",()=>openCreate("students"),GraduationCap],["Добавить родителя",()=>openCreate("parents"),UsersRound],["Добавить учителя",()=>openCreate("teachers"),UserRound],["Создать группу",()=>location.assign("/admin/groups"),Layers3],["Перевести ученика",()=>location.assign("/admin/students?action=transfer"),ArrowLeftRight],["Создать учебник",()=>location.assign("/admin/books"),BookOpen]];
  const attention=[
    [students.filter(s=>!s.parentIds.length).length,"Ученики без родителя","/admin/students"],
    [groups.filter(g=>!g.teacherId).length,"Группы без учителя","/admin/groups"],
    [students.filter(s=>!s.groupId).length,"Ученики без активной группы","/admin/students"],
    [groups.filter(g=>!g.bookId).length,"Группы без учебника","/admin/groups"],
  ] as const;
  return <div className="admin-dashboard">
    <section className="admin-welcome"><div><p>Добро пожаловать, Марина</p><h2>Управление учебным центром</h2><span>Happy Town · период 2025–2026 · данные обновлены 1 августа 2026, 10:42</span></div><Badge status="active"/></section>
    <div className="admin-stat-grid">{stats.map(([Icon,label,value,note])=><article className="admin-stat" key={label}><span><Icon size={19}/></span><div><small>{label}</small><strong>{value}</strong><p>{note}</p></div></article>)}</div>
    <section className="section-card"><div className="section-head"><h2>Быстрые действия</h2><span className="muted">Частые операции</span></div><div className="admin-quick">{quickActions.map(([label,onClick,Icon])=><button key={label} onClick={onClick}><span><Icon size={19}/></span>{label}<ChevronRight size={16}/></button>)}</div></section>
    <div className="admin-dashboard-grid"><section className="section-card"><div className="section-head"><h2>Посещаемость</h2><span className="badge green">6 месяцев</span></div><div className="mini-chart"><div className="chart-scale"><span>100%</span><span>50%</span><span>0%</span></div>{attendance.map((v,i)=><div key={i}><i style={{height:`${v}%`}}/><span>{["Мар","Апр","Май","Июн","Июл","Авг"][i]}</span></div>)}</div></section><section className="section-card"><div className="section-head"><h2>Занятия по месяцам</h2><span className="badge blue">Всего 272</span></div><div className="line-bars">{lessons.map((v,i)=><div key={i}><span>{v}</span><i style={{height:`${v/58*100}%`}}/><small>{["Мар","Апр","Май","Июн","Июл","Авг"][i]}</small></div>)}</div></section></div>
    <div className="admin-dashboard-grid"><section className="section-card attention-card"><div className="section-head"><h2>Требует внимания</h2><AlertTriangle size={19}/></div>{attention.map(([count,label,href])=><Link href={href} key={label}><b>{count}</b><span>{label}</span><ChevronRight size={17}/></Link>)}</section><section className="section-card"><div className="section-head"><h2>Последние действия</h2><Link href="/admin/history">Весь журнал</Link></div><div className="admin-events">{auditLog.slice(0,4).map(entry=><div key={entry.id}><span><History size={16}/></span><p><b>{entry.action} · {entry.entity}</b><small>{entry.date} · {entry.actor}</small></p></div>)}</div></section></div>
  </div>;
}

function PersonForm({ kind, item, groups, onClose, onSave }: { kind:EntityKind;item?:PersonEntity;groups:AdminGroup[];onClose:()=>void;onSave:(item:PersonEntity)=>void }) {
  const editing=Boolean(item); const student=item&&"birthDate" in item?item:undefined; const [name,setName]=useState(item?.name??""); const [phone,setPhone]=useState(item&&"phone" in item?item.phone:""); const [email,setEmail]=useState(item&&"email" in item?item.email:""); const [birthDate,setBirthDate]=useState(student?.birthDate??""); const [level,setLevel]=useState(student?.level??"Starter"); const [groupId,setGroupId]=useState(student?.groupId??""); const [error,setError]=useState("");
  const submit=(e:React.FormEvent)=>{e.preventDefault();if(!name.trim()){setError("Укажите имя");return}if(kind==="parents"&&!phone.trim()){setError("Для родителя обязателен телефон");return}if(email&&!/^\S+@\S+\.\S+$/.test(email)){setError("Проверьте формат email");return}if(kind==="students"&&birthDate&&new Date(birthDate)>new Date()){setError("Дата рождения не может быть в будущем");return}const id=item?.id??`${kind[0]}${Date.now()}`;if(kind==="students")onSave({id,name,birthDate,level,groupId:groupId||undefined,parentIds:student?.parentIds??[],status:item?.status??"active"});else if(kind==="teachers")onSave({id,name,phone,email,groupIds:item&&"groupIds" in item?item.groupIds:[],status:item?.status??"active"});else onSave({id,name,phone,email,studentIds:item&&"studentIds" in item?item.studentIds:[],status:item?.status??"active"})};
  return <Modal title={`${editing?"Редактировать":"Добавить"} ${labels[kind]}`} onClose={onClose}><form onSubmit={submit} className="admin-form"><label><span>Имя *</span><input value={name} onChange={e=>setName(e.target.value)} placeholder="Имя и фамилия" autoFocus/></label>{kind!=="students"&&<><label><span>Телефон {kind==="parents"&&"*"}</span><input value={phone} onChange={e=>setPhone(e.target.value)} placeholder="+7 700 000 00 00"/></label><label><span>Email</span><input value={email} onChange={e=>setEmail(e.target.value)} placeholder="name@example.com"/></label></>}{kind==="students"&&<><label><span>Дата рождения</span><input type="date" value={birthDate.includes(".")?"":birthDate} onChange={e=>setBirthDate(e.target.value)}/></label><label><span>Уровень</span><select value={level} onChange={e=>setLevel(e.target.value)}><option>Starter</option><option>Beginner</option><option>Elementary</option></select></label><label><span>Группа</span><select value={groupId} onChange={e=>setGroupId(e.target.value)}><option value="">Без группы</option>{groups.map(g=><option value={g.id} key={g.id}>{g.name}</option>)}</select></label></>}{error&&<p className="form-error">{error}</p>}<div className="admin-form-actions"><button type="button" className="btn secondary" onClick={onClose}>Отмена</button><button className="btn" type="submit">{editing?"Сохранить":"Создать"}</button></div></form></Modal>;
}

function PeoplePage({ kind, items, groups, onSave, onArchive, requestedCreate=false }: { kind:EntityKind;items:PersonEntity[];groups:AdminGroup[];onSave:(item:PersonEntity)=>void;onArchive:(item:PersonEntity)=>void;requestedCreate?:boolean }) {
  const [query,setQuery]=useState(""); const [form,setForm]=useState<PersonEntity|"new"|null>(requestedCreate?"new":null); const [view,setView]=useState<PersonEntity|null>(null); const [archive,setArchive]=useState<PersonEntity|null>(null); const [page,setPage]=useState(1); const pageSize=8;
  const filtered=items.filter(item=>JSON.stringify(item).toLowerCase().includes(query.toLowerCase())); const visible=filtered.slice((page-1)*pageSize,page*pageSize);
  const columns=kind==="teachers"?["Учитель","Контакты","Группы","Статус"]:kind==="parents"?["Родитель","Телефон","Дети","Статус"]:["Ученик","Возраст / уровень","Группа","Родители","Статус"];
  const values=(item:PersonEntity)=>kind==="teachers"?[item.name,(item as Teacher).email,`${(item as Teacher).groupIds.length} группы`,<Badge status={item.status} key="b"/>]:kind==="parents"?[item.name,(item as Parent).phone,`${(item as Parent).studentIds.length} ребёнка`,<Badge status={item.status} key="b"/>]:[item.name,`${(item as AdminStudent).birthDate} · ${(item as AdminStudent).level}`,groups.find(g=>g.id===(item as AdminStudent).groupId)?.name??"Не назначена",`${(item as AdminStudent).parentIds.length} связей`,<Badge status={item.status} key="b"/>];
  return <><Toolbar query={query} setQuery={setQuery} action={<button className="btn" onClick={()=>setForm("new")}><Plus size={17}/>Добавить</button>}/><section className="section-card admin-table-card"><div className="admin-table-wrap"><table><thead><tr>{columns.map(c=><th key={c}>{c}</th>)}<th>Действия</th></tr></thead><tbody>{visible.map(item=><tr key={item.id}>{values(item).map((value,i)=><td key={i}>{value}</td>)}<td><div className="row-actions"><button onClick={()=>setView(item)} aria-label="Просмотреть"><Eye size={16}/></button><button onClick={()=>setForm(item)} aria-label="Редактировать"><Edit3 size={16}/></button><button onClick={()=>setArchive(item)} aria-label="Архивировать"><Archive size={16}/></button></div></td></tr>)}</tbody></table></div><div className="admin-mobile-list">{visible.map(item=><article key={item.id}><div><span className="avatar">{item.name.split(" ").map(x=>x[0]).slice(0,2).join("")}</span><div><h3>{item.name}</h3><p>{values(item).slice(1,-1).map(String).join(" · ")}</p></div>{values(item).at(-1)}</div><div><button onClick={()=>setView(item)}><Eye size={16}/>Открыть</button><button onClick={()=>setForm(item)}><Edit3 size={16}/>Изменить</button><button onClick={()=>setArchive(item)}><Archive size={16}/></button></div></article>)}</div><div className="admin-pagination"><span>Показано {visible.length} из {filtered.length}</span><div><button disabled={page===1} onClick={()=>setPage(p=>p-1)}>Назад</button><b>{page}</b><button disabled={page*pageSize>=filtered.length} onClick={()=>setPage(p=>p+1)}>Вперёд</button></div></div></section>{form&&<PersonForm kind={kind} item={form==="new"?undefined:form} groups={groups} onClose={()=>setForm(null)} onSave={item=>{onSave(item);setForm(null)}}/>}{archive&&<Confirm title={`Архивировать ${labels[kind]}?`} text={`${archive.name} станет недоступен в активных списках. Запись можно восстановить из архива.`} confirm="Архивировать" danger onClose={()=>setArchive(null)} onConfirm={()=>{onArchive(archive);setArchive(null)}}/>}{view&&<Modal title={view.name} onClose={()=>setView(null)}><div className="entity-detail"><span className="avatar big">{view.name.split(" ").map(x=>x[0]).slice(0,2).join("")}</span><Badge status={view.status}/><dl>{Object.entries(view).filter(([key])=>!['id','status'].includes(key)).map(([key,value])=><div key={key}><dt>{({name:"Имя",phone:"Телефон",email:"Email",birthDate:"Дата рождения",level:"Уровень",groupId:"Группа",parentIds:"Родители",studentIds:"Дети",groupIds:"Группы"} as Record<string,string>)[key]??key}</dt><dd>{Array.isArray(value)?value.length:String(value||"—")}</dd></div>)}</dl><button className="btn" onClick={()=>{setForm(view);setView(null)}}><Edit3 size={16}/>Редактировать</button></div></Modal>}</>;
}

function GroupsPage({ groups, setGroups, teachers, notify }: { groups:AdminGroup[];setGroups:React.Dispatch<React.SetStateAction<AdminGroup[]>>;teachers:Teacher[];notify:(text:string)=>void }) {
  const [query,setQuery]=useState(""); const [editing,setEditing]=useState<AdminGroup|null>(null); const [assigning,setAssigning]=useState<AdminGroup|null>(null); const [name,setName]=useState("");
  const save=()=>{if(!name.trim())return;const row:AdminGroup=editing?{...editing,name}:{id:`g${Date.now()}`,name,level:"Starter",periodId:"ap1",capacity:10,studentIds:[],status:"active"};setGroups(prev=>editing?prev.map(g=>g.id===row.id?row:g):[row,...prev]);setEditing(null);setName("");notify("Группа сохранена")};
  return <><Toolbar query={query} setQuery={setQuery} action={<button className="btn" onClick={()=>{setEditing({} as AdminGroup);setName("")}}><Plus size={17}/>Создать группу</button>}/><div className="admin-group-grid">{groups.filter(g=>g.name.toLowerCase().includes(query.toLowerCase())).map(group=><article className="section-card" key={group.id}><div className="group-card-head"><span><Layers3/></span><div><Badge status={group.status}/><h3>{group.name}</h3><p>{group.level} · {group.studentIds.length} из {group.capacity} учеников</p></div></div><dl><div><dt>Учитель</dt><dd>{teachers.find(t=>t.id===group.teacherId)?.name??<em>Не назначен</em>}</dd></div><div><dt>Учебник</dt><dd>{books.find(b=>b.id===group.bookId)?.title??"Не назначен"}</dd></div><div><dt>Период</dt><dd>{academicPeriods.find(p=>p.id===group.periodId)?.name}</dd></div></dl><div className="capacity"><span>Наполняемость</span><b>{Math.round(group.studentIds.length/group.capacity*100)}%</b><i><u style={{width:`${group.studentIds.length/group.capacity*100}%`}}/></i></div><div className="card-actions"><button onClick={()=>setAssigning(group)}>Назначить учителя</button><button onClick={()=>{setEditing(group);setName(group.name)}}><Edit3 size={16}/></button></div></article>)}</div>{editing&&<Modal title={editing.id?"Редактировать группу":"Создать группу"} onClose={()=>setEditing(null)}><div className="admin-form"><label><span>Название *</span><input value={name} onChange={e=>setName(e.target.value)} placeholder="Например, Kids Starter" autoFocus/></label><label><span>Учебный период *</span><select><option>2025–2026</option></select></label><label><span>Учебник *</span><select>{books.map(b=><option key={b.id}>{b.title}</option>)}</select></label><label><span>Максимум учеников *</span><input type="number" min="1" defaultValue="10"/></label><div className="admin-form-actions"><button className="btn secondary" onClick={()=>setEditing(null)}>Отмена</button><button className="btn" onClick={save}>Сохранить</button></div></div></Modal>}{assigning&&<Modal title="Назначить учителя" onClose={()=>setAssigning(null)}><div className="admin-form"><p className="muted">Группа: <b>{assigning.name}</b></p><label><span>Учитель</span><select defaultValue={assigning.teacherId} id="teacherAssign"><option value="">Не назначен</option>{teachers.filter(t=>t.status==="active").map(t=><option value={t.id} key={t.id}>{t.name} · {t.groupIds.length} группы</option>)}</select></label><div className="admin-form-actions"><button className="btn secondary" onClick={()=>setAssigning(null)}>Отмена</button><button className="btn" onClick={()=>{const select=document.getElementById("teacherAssign") as HTMLSelectElement;setGroups(prev=>prev.map(g=>g.id===assigning.id?{...g,teacherId:select.value||undefined}:g));setAssigning(null);notify("Учитель назначен группе")}}>Назначить</button></div></div></Modal>}</>;
}

function CurriculumPage({ page, notify }: { page:string;notify:(t:string)=>void }) {
  const source=page==="courses"?courses:page==="books"?books:page==="periods"?academicPeriods:page==="skills"?skillCategories:[]; const [query,setQuery]=useState(""); const [form,setForm]=useState(false);
  if(page==="units"||page==="topics")return <CurriculumEditor notify={notify}/>;
  const title=({courses:"курс",books:"учебник",periods:"учебный период",skills:"категорию навыка"} as Record<string,string>)[page];
  return <><Toolbar query={query} setQuery={setQuery} action={<button className="btn" onClick={()=>setForm(true)}><Plus size={17}/>Добавить</button>}/><div className="admin-catalog-grid">{source.filter(item=>JSON.stringify(item).toLowerCase().includes(query.toLowerCase())).map(item=>{const row=item as unknown as Record<string,unknown>;const name=String(row.name??row.title??"Без названия");const note=row.description??row.publisher??(row.startDate?`${row.startDate} — ${row.endDate}`:`Максимум: ${row.maxScore??10}`);return <article className="section-card" key={item.id}><div className="catalog-icon">{page==="books"?<BookOpen/>:page==="periods"?<CalendarDays/>:page==="skills"?<Sparkles/>:<GraduationCap/>}</div><Badge status={item.status}/><h3>{name}</h3><p>{String(note)}</p><div className="card-actions"><button onClick={()=>setForm(true)}><Edit3 size={16}/>Изменить</button><button onClick={()=>notify("Запись подготовлена к архивированию")}><Archive size={16}/></button></div></article>})}</div>{form&&<Modal title={`Добавить ${title}`} onClose={()=>setForm(false)}><div className="admin-form"><label><span>Название *</span><input placeholder="Введите название" autoFocus/></label>{page==="periods"&&<div className="form-row"><label><span>Дата начала *</span><input type="date"/></label><label><span>Дата окончания *</span><input type="date"/></label></div>}<label><span>Описание</span><textarea placeholder="Краткое описание"/></label><div className="admin-form-actions"><button className="btn secondary" onClick={()=>setForm(false)}>Отмена</button><button className="btn" onClick={()=>{setForm(false);notify("Запись сохранена в demo-режиме")}}>Сохранить</button></div></div></Modal>}</>;
}

function CurriculumEditor({ notify }: { notify:(t:string)=>void }) {
  const [selected,setSelected]=useState(units[0].id); const [draft,setDraft]=useState(false);
  return <div className="curriculum-layout"><aside className="section-card"><div className="section-head"><h2>Структура учебника</h2><button className="icon-add" onClick={()=>setDraft(true)}><Plus/></button></div><select><option>Family and Friends 1</option>{books.slice(1).map(b=><option key={b.id}>{b.title}</option>)}</select><div className="unit-tree">{units.slice(0,3).map(unit=><button className={selected===unit.id?"active":""} onClick={()=>setSelected(unit.id)} key={unit.id}><Layers3 size={16}/><span>{unit.title}<small>{unit.topicIds.length} темы</small></span><ChevronRight size={15}/></button>)}</div></aside><section className="section-card curriculum-main"><div className="section-head"><div><span className="eyebrow">Редактор программы</span><h2>{units.find(u=>u.id===selected)?.title}</h2></div><button className="btn" onClick={()=>setDraft(true)}><Plus size={16}/>Добавить тему</button></div><p className="muted">Перетаскивание будет подключено к backend на следующем этапе. Сейчас порядок меняется локально кнопками.</p><div className="topic-list">{topics.filter(t=>t.unitId===selected).map((topic,index)=><article key={topic.id}><span>{index+1}</span><div><h3>{topic.title}</h3><p>Статус: опубликована · 2 занятия</p></div><button onClick={()=>notify("Тема перемещена выше")} disabled={index===0}>↑</button><button onClick={()=>notify("Тема открыта для редактирования")}><Edit3 size={16}/></button></article>)}</div></section>{draft&&<Modal title="Новая тема" onClose={()=>setDraft(false)}><div className="admin-form"><label><span>Название *</span><input placeholder="Название темы" autoFocus/></label><label><span>Краткое описание</span><textarea placeholder="Цели и содержание темы"/></label><div className="admin-form-actions"><button className="btn secondary" onClick={()=>setDraft(false)}>Отмена</button><button className="btn" onClick={()=>{setDraft(false);notify("Тема добавлена в demo-режиме")}}>Добавить тему</button></div></div></Modal>}</div>;
}

function TransferAndLinks({ students, setStudents, parents, groups, notify }: { students:AdminStudent[];setStudents:React.Dispatch<React.SetStateAction<AdminStudent[]>>;parents:Parent[];groups:AdminGroup[];notify:(t:string)=>void }) {
  const [tab,setTab]=useState<"links"|"transfer">("links"); const [studentId,setStudentId]=useState(students[0].id); const [target,setTarget]=useState(""); const [parentId,setParentId]=useState("");
  return <section className="section-card admin-operation"><div className="tabs"><button className={tab==="links"?"active":""} onClick={()=>setTab("links")}>Привязка родителя</button><button className={tab==="transfer"?"active":""} onClick={()=>setTab("transfer")}>Перевод ученика</button></div><div className="operation-grid"><div><span className="step">1</span><label><b>Ученик</b><select value={studentId} onChange={e=>setStudentId(e.target.value)}>{students.map(s=><option value={s.id} key={s.id}>{s.name}</option>)}</select></label></div><div><span className="step">2</span>{tab==="links"?<label><b>Родитель</b><select value={parentId} onChange={e=>setParentId(e.target.value)}><option value="">Выберите родителя</option>{parents.map(p=><option value={p.id} key={p.id}>{p.name} · {p.phone}</option>)}</select></label>:<label><b>Новая группа</b><select value={target} onChange={e=>setTarget(e.target.value)}><option value="">Выберите группу</option>{groups.filter(g=>g.id!==students.find(s=>s.id===studentId)?.groupId).map(g=><option value={g.id} key={g.id}>{g.name} · {g.studentIds.length}/{g.capacity}</option>)}</select></label>}</div><div className="operation-summary"><b>Проверка</b><p>{tab==="links"?"Связь появится в профилях родителя и ребёнка.":"Текущая группа будет сохранена в истории обучения."}</p><button className="btn" disabled={tab==="links"?!parentId:!target} onClick={()=>{if(tab==="links")setStudents(prev=>prev.map(s=>s.id===studentId?{...s,parentIds:[...new Set([...s.parentIds,parentId])]}:s));else setStudents(prev=>prev.map(s=>s.id===studentId?{...s,groupId:target}:s));notify(tab==="links"?"Родитель привязан к ученику":"Ученик переведён, событие добавлено в историю");setTarget("");setParentId("")}}>{tab==="links"?"Создать связь":"Перевести ученика"}</button></div></div></section>;
}

function HistoryPage() { const [tab,setTab]=useState("learning"); const [query,setQuery]=useState(""); const data=tab==="learning"?initialHistory:auditLog; return <><div className="tabs"><button className={tab==="learning"?"active":""} onClick={()=>setTab("learning")}>История обучения</button><button className={tab==="audit"?"active":""} onClick={()=>setTab("audit")}>Журнал изменений</button></div><Toolbar query={query} setQuery={setQuery}/><section className="section-card"><div className="admin-log">{data.filter(row=>JSON.stringify(row).toLowerCase().includes(query.toLowerCase())).map(row=><article key={row.id}><span><History size={17}/></span><div><time>{row.date}</time><h3>{"title" in row?row.title:`${row.action} · ${row.entity}`}</h3><p>{row.details}</p></div>{"type" in row&&<span className="badge blue">{row.type}</span>}</article>)}</div></section></> }

function ArchivePage({ items, setItems, notify }: { items:ArchivedEntity[];setItems:React.Dispatch<React.SetStateAction<ArchivedEntity[]>>;notify:(t:string)=>void }) { const [query,setQuery]=useState(""); const [restore,setRestore]=useState<ArchivedEntity|null>(null); return <><Toolbar query={query} setQuery={setQuery}/><section className="section-card admin-table-card"><div className="admin-table-wrap"><table><thead><tr><th>Название</th><th>Тип</th><th>Причина</th><th>Дата архивации</th><th>Действие</th></tr></thead><tbody>{items.filter(i=>JSON.stringify(i).toLowerCase().includes(query.toLowerCase())).map(item=><tr key={item.id}><td><b>{item.name}</b></td><td><span className="badge gray">{item.entityType}</span></td><td>{item.reason}</td><td>{item.archivedAt}</td><td><button className="restore-btn" onClick={()=>setRestore(item)}><RefreshCw size={15}/>Восстановить</button></td></tr>)}</tbody></table></div></section>{restore&&<Confirm title="Восстановить запись?" text={`${restore.name} вернётся в активный список. Связи будут восстановлены по исходному ID.`} confirm="Восстановить" onClose={()=>setRestore(null)} onConfirm={()=>{setItems(prev=>prev.filter(i=>i.id!==restore.id));setRestore(null);notify("Запись восстановлена")}}/>}</> }

function ProfilePage({ notify }: { notify:(t:string)=>void }) { const [editing,setEditing]=useState(false); return <div className="admin-profile-grid"><section className="section-card"><div className="profile-hero"><span className="avatar big">МС</span><div><Badge status="active"/><h2>{adminUser.name}</h2><p>Администратор Happy Town</p></div></div><dl className="profile-dl"><div><dt>Телефон</dt><dd>{adminUser.phone}</dd></div><div><dt>Email</dt><dd>{adminUser.email}</dd></div><div><dt>Роль</dt><dd>ADMIN</dd></div><div><dt>Создан</dt><dd>{adminUser.createdAt}</dd></div></dl><button className="btn" onClick={()=>setEditing(true)}><Edit3 size={16}/>Редактировать</button></section><section className="section-card"><div className="section-head"><h2>Последние действия</h2><ShieldCheck/></div><div className="admin-events">{auditLog.slice(0,4).map(e=><div key={e.id}><span><ClipboardList size={16}/></span><p><b>{e.action} · {e.entity}</b><small>{e.date}</small></p></div>)}</div></section>{editing&&<Modal title="Редактировать профиль" onClose={()=>setEditing(false)}><div className="admin-form"><label><span>Имя *</span><input defaultValue={adminUser.name}/></label><label><span>Телефон</span><input defaultValue={adminUser.phone}/></label><label><span>Email</span><input defaultValue={adminUser.email}/></label><div className="admin-form-actions"><button className="btn secondary" onClick={()=>setEditing(false)}>Отмена</button><button className="btn" onClick={()=>{setEditing(false);notify("Профиль обновлён")}}>Сохранить</button></div></div></Modal>}</div> }

export function AdminPortal({ page }: { page:string }) {
  const [teachers,setTeachers]=useState(initialTeachers); const [parents,setParents]=useState(initialParents); const [students,setStudents]=useState(initialStudents); const [groups,setGroups]=useState(initialGroups); const [archived,setArchived]=useState(initialArchived); const [toast,setToast]=useState<Toast>(null); const [dashboardCreate,setDashboardCreate]=useState<EntityKind|null>(null);
  const notify=(text:string,tone:"success"|"danger"="success")=>{setToast({text,tone});window.setTimeout(()=>setToast(null),2800)};
  const save=(kind:EntityKind,item:PersonEntity)=>{if(kind==="teachers")setTeachers(prev=>upsert(prev,item as Teacher));if(kind==="parents")setParents(prev=>upsert(prev,item as Parent));if(kind==="students")setStudents(prev=>upsert(prev,item as AdminStudent));notify("Изменения сохранены")};
  const archive=(kind:EntityKind,item:PersonEntity)=>{const record:ArchivedEntity={id:`ar${Date.now()}`,sourceId:item.id,entityType:kind==="teachers"?"Учитель":kind==="parents"?"Родитель":"Ученик",name:item.name,reason:"Архивировано администратором",archivedAt:"01.08.2026"};setArchived(prev=>[record,...prev]);if(kind==="teachers")setTeachers(prev=>prev.filter(x=>x.id!==item.id));if(kind==="parents")setParents(prev=>prev.filter(x=>x.id!==item.id));if(kind==="students")setStudents(prev=>prev.filter(x=>x.id!==item.id));notify("Запись перемещена в архив")};
  const content=(()=>{if(page==="home")return <Dashboard students={students} teachers={teachers} parents={parents} groups={groups} openCreate={setDashboardCreate}/>;if(["teachers","parents","students"].includes(page)){const kind=page as EntityKind;const source=kind==="teachers"?teachers:kind==="parents"?parents:students;return <><PeoplePage kind={kind} items={source} groups={groups} onSave={item=>save(kind,item)} onArchive={item=>archive(kind,item)}/>{kind==="students"&&<TransferAndLinks students={students} setStudents={setStudents} parents={parents} groups={groups} notify={notify}/>}</>}if(page==="groups")return <GroupsPage groups={groups} setGroups={setGroups} teachers={teachers} notify={notify}/>;if(["courses","books","units","topics","periods","skills"].includes(page))return <CurriculumPage page={page} notify={notify}/>;if(page==="history")return <HistoryPage/>;if(page==="archive")return <ArchivePage items={archived} setItems={setArchived} notify={notify}/>;if(page==="profile")return <ProfilePage notify={notify}/>;return <Dashboard students={students} teachers={teachers} parents={parents} groups={groups} openCreate={setDashboardCreate}/>})();
  return <>{content}{dashboardCreate&&<PersonForm kind={dashboardCreate} groups={groups} onClose={()=>setDashboardCreate(null)} onSave={item=>{save(dashboardCreate,item);setDashboardCreate(null)}}/>}{toast&&<div className={`admin-toast ${toast.tone}`}><Check size={17}/>{toast.text}</div>}</>;
}

function upsert<T extends {id:string}>(items:T[],item:T){return items.some(x=>x.id===item.id)?items.map(x=>x.id===item.id?item:x):[item,...items]}
