"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { BookOpen, Check, Edit3, FileText, Layers3, LoaderCircle, Plus, Sparkles, Trash2, X } from "lucide-react";
import type { AdminCatalogData, AdminCatalogKind } from "../lib/types/admin-api";
import { EntityStatusBadge } from "./ui/entity-status-badge";

type CatalogItem=AdminCatalogData["books"][number]|AdminCatalogData["units"][number]|AdminCatalogData["skills"][number];
type Props={kind:AdminCatalogKind;data:AdminCatalogData};
const labels={books:{one:"учебник",title:"Учебники",add:"Добавить учебник",description:"Учебные материалы, доступные при создании групп."},units:{one:"раздел",title:"Разделы",add:"Добавить раздел",description:"Структура учебников и последовательность обучения."},skills:{one:"категорию навыков",title:"Категории навыков",add:"Добавить категорию",description:"Единые критерии для оценивания прогресса учеников."}} as const;

async function requestJson(url:string,options?:RequestInit){const response=await fetch(url,{...options,headers:{"content-type":"application/json",...(options?.headers||{})}});const payload=await response.json();if(!response.ok)throw new Error(payload.error||"Не удалось выполнить операцию");return payload}
function Modal({title,onClose,children}:{title:string;onClose:()=>void;children:React.ReactNode}){return <div className="admin-modal-layer" onMouseDown={event=>event.target===event.currentTarget&&onClose()}><section className="admin-modal catalog-modal" role="dialog" aria-modal="true" aria-label={title}><header><div><span>Happy Town</span><h2>{title}</h2></div><button type="button" onClick={onClose} aria-label="Закрыть"><X size={20}/></button></header>{children}</section></div>}

export function AdminCatalogManager({kind,data}:Props){
  const router=useRouter();const [form,setForm]=useState<CatalogItem|"new"|null>(null);const [removing,setRemoving]=useState<CatalogItem|null>(null);const [toast,setToast]=useState<{text:string;tone:"success"|"danger"}|null>(null);const [busy,setBusy]=useState(false);
  const items=kind==="books"?data.books:kind==="units"?data.units:data.skills;const copy=labels[kind];
  function notify(text:string,tone:"success"|"danger"="success"){setToast({text,tone});window.setTimeout(()=>setToast(null),3000)}
  async function remove(){if(!removing)return;setBusy(true);try{await requestJson(`/api/admin/catalog/${kind}/${removing.id}`,{method:"DELETE"});setRemoving(null);notify(`${kind==="skills"?"Категория":kind==="units"?"Раздел":"Учебник"} перемещён${kind==="skills"?"а":""} в архив`);router.refresh()}catch(error){notify(error instanceof Error?error.message:"Удаление не выполнено","danger")}finally{setBusy(false)}}
  return <div className={`catalog-manager catalog-manager-${kind}`}><section className="catalog-toolbar"><div><span className="catalog-kicker">Учебная структура</span><h2>{copy.title}</h2><p>{copy.description}</p></div><button className="btn" onClick={()=>setForm("new")}><Plus size={17}/>{copy.add}</button></section>{items.length?<div className="catalog-entity-grid">{items.map(item=><CatalogEntityCard key={item.id} kind={kind} item={item} onEdit={()=>setForm(item)} onRemove={kind==="units"?undefined:()=>setRemoving(item)}/>)}</div>:<section className="catalog-empty"><span>{kind==="books"?<BookOpen/>:kind==="units"?<Layers3/>:<Sparkles/>}</span><h3>Список пока пуст</h3><p>Добавьте {copy.one}, чтобы запись появилась здесь.</p><button className="btn" onClick={()=>setForm("new")}><Plus size={17}/>{copy.add}</button></section>}{kind==="units"&&<TopicOverview topics={data.topics}/>} {form&&<CatalogForm kind={kind} item={form==="new"?undefined:form} data={data} onClose={()=>setForm(null)} onSaved={message=>{setForm(null);notify(message);router.refresh()}}/>}{removing&&<Modal title={`Удалить ${copy.one}?`} onClose={()=>setRemoving(null)}><div className="catalog-delete-copy"><span><Trash2 size={21}/></span><div><h3>{removing.name}</h3><p>{kind==="books"?"Учебник будет перемещён в архив. Если он используется активной группой, удаление будет безопасно заблокировано.":"Категория перестанет отображаться в активном списке, а выставленные ранее оценки сохранятся."}</p></div></div><div className="admin-form-actions"><button className="btn secondary" onClick={()=>setRemoving(null)}>Отмена</button><button className="btn danger-btn" disabled={busy} onClick={()=>void remove()}>{busy?<><LoaderCircle className="spin" size={17}/>Удаляем…</>:"Удалить"}</button></div></Modal>}{toast&&<div className={`admin-toast ${toast.tone}`}><Check size={17}/>{toast.text}</div>}</div>
}

function TopicOverview({topics}:{topics:AdminCatalogData["topics"]}){return <section className="catalog-topic-section"><div><span className="catalog-card-icon"><FileText size={19}/></span><div><h2>Темы</h2><p>Темы внутри разделов сохранены без изменений.</p></div></div>{topics.length?<div className="catalog-topic-grid">{topics.map(topic=><article key={topic.id}><div><span>{topic.unitName}</span><EntityStatusBadge status={topic.status}/></div><h3>{topic.name}</h3><p>{topic.description||"Описание не указано"}</p></article>)}</div>:<p className="admin-empty compact">Темы пока не добавлены.</p>}</section>}

function CatalogEntityCard({kind,item,onEdit,onRemove}:{kind:AdminCatalogKind;item:CatalogItem;onEdit:()=>void;onRemove?:()=>void}){
  if(kind==="books"){const book=item as AdminCatalogData["books"][number];return <article className="catalog-entity-card"><div className="catalog-card-top"><span className="catalog-card-icon"><BookOpen size={20}/></span><EntityStatusBadge status={book.status}/></div><div className="catalog-card-content"><h3>{book.name}</h3><p>{book.description||"Описание не указано"}</p><dl><div><dt>Уровень</dt><dd>{book.level}</dd></div><div><dt>Разделов</dt><dd>{book.unitCount}</dd></div>{book.author&&<div><dt>Автор</dt><dd>{book.author}</dd></div>}{book.publisher&&<div><dt>Издательство</dt><dd>{book.publisher}</dd></div>}</dl></div><CardActions onEdit={onEdit} onRemove={onRemove}/></article>}
  if(kind==="units"){const unit=item as AdminCatalogData["units"][number];return <article className="catalog-entity-card"><div className="catalog-card-top"><span className="catalog-card-icon"><Layers3 size={20}/></span><EntityStatusBadge status={unit.status}/></div><div className="catalog-card-content"><span className="catalog-parent-label">{unit.bookName}</span><h3>{unit.name}</h3><p>{unit.description||"Описание не указано"}</p><dl><div><dt>Тем</dt><dd>{unit.topicCount}</dd></div></dl></div><CardActions onEdit={onEdit}/></article>}
  const skill=item as AdminCatalogData["skills"][number];return <article className="catalog-entity-card skill-category-card"><div className="catalog-card-top"><span className="skill-code">{skill.code}</span><EntityStatusBadge status={skill.isActive?"active":"inactive"}/></div><div className="catalog-card-content"><h3>{skill.name}</h3><p>{skill.description||"Описание не указано"}</p></div><CardActions onEdit={onEdit} onRemove={onRemove}/></article>
}
function CardActions({onEdit,onRemove}:{onEdit:()=>void;onRemove?:()=>void}){return <div className="catalog-card-actions"><button onClick={onEdit}><Edit3 size={16}/>Редактировать</button>{onRemove&&<button className="danger-link" onClick={onRemove} aria-label="Удалить"><Trash2 size={16}/></button>}</div>}

function CatalogForm({kind,item,data,onClose,onSaved}:{kind:AdminCatalogKind;item?:CatalogItem;data:AdminCatalogData;onClose:()=>void;onSaved:(message:string)=>void}){
  const book=item&&kind==="books"?item as AdminCatalogData["books"][number]:undefined;const unit=item&&kind==="units"?item as AdminCatalogData["units"][number]:undefined;const skill=item&&kind==="skills"?item as AdminCatalogData["skills"][number]:undefined;
  const [name,setName]=useState(item?.name??"");const [description,setDescription]=useState(item?.description??"");const [author,setAuthor]=useState(book?.author??"");const [publisher,setPublisher]=useState(book?.publisher??"");const [level,setLevel]=useState(book?.level??"Starter");const [bookId,setBookId]=useState(unit?.bookId??data.books[0]?.id??"");const [code,setCode]=useState(skill?.code??"");const [active,setActive]=useState(skill?.isActive??true);const [status,setStatus]=useState((book?.status??unit?.status??"active").toUpperCase());const [busy,setBusy]=useState(false);const [error,setError]=useState("");
  async function submit(event:React.FormEvent){event.preventDefault();setBusy(true);setError("");try{const payload=kind==="books"?{name,description,author,publisher,level,...(item?{status}:{})}:kind==="units"?{name,description,...(item?{status}:{bookId})}:{name,description,code,isActive:active};await requestJson(item?`/api/admin/catalog/${kind}/${item.id}`:"/api/admin/catalog",{method:item?"PATCH":"POST",body:JSON.stringify(item?{data:payload}:{kind,data:payload})});onSaved(item?"Изменения сохранены":"Запись добавлена")}catch(reason){setError(reason instanceof Error?reason.message:"Ошибка сохранения")}finally{setBusy(false)}}
  return <Modal title={`${item?"Редактировать":"Добавить"} ${labels[kind].one}`} onClose={onClose}><form className="admin-form catalog-form" onSubmit={submit}>{kind==="skills"&&<label><span>Код *</span><input value={code} onChange={event=>setCode(event.target.value.toUpperCase())} required maxLength={30} placeholder="Например, SPEAKING" autoFocus/></label>}<label><span>Название *</span><input value={name} onChange={event=>setName(event.target.value)} required autoFocus={kind!=="skills"}/></label>{kind==="books"&&<><div className="form-row"><label><span>Автор</span><input value={author} onChange={event=>setAuthor(event.target.value)}/></label><label><span>Издательство</span><input value={publisher} onChange={event=>setPublisher(event.target.value)}/></label></div><label><span>Уровень *</span><input value={level} onChange={event=>setLevel(event.target.value)} required placeholder="Starter, A1, A2…"/></label></>}{kind==="units"&&!item&&<label><span>Учебник *</span><select value={bookId} onChange={event=>setBookId(event.target.value)} required><option value="">Выберите учебник</option>{data.books.map(option=><option key={option.id} value={option.id}>{option.name}</option>)}</select></label>}<label><span>Описание</span><textarea value={description} onChange={event=>setDescription(event.target.value)} rows={4} placeholder="Краткое понятное описание"/></label>{item&&kind!=="skills"&&<label><span>Статус</span><select value={status} onChange={event=>setStatus(event.target.value)}><option value="ACTIVE">Активен</option><option value="INACTIVE">Неактивен</option></select></label>}{kind==="skills"&&<label className="catalog-switch"><input type="checkbox" checked={active} onChange={event=>setActive(event.target.checked)}/><span><b>Активная категория</b><small>Доступна при оценивании учеников</small></span></label>}{error&&<p className="form-error">{error}</p>}<div className="admin-form-actions sticky"><button type="button" className="btn secondary" onClick={onClose}>Отмена</button><button className="btn" disabled={busy}>{busy?<><LoaderCircle className="spin" size={17}/>Сохраняем…</>:"Сохранить"}</button></div></form></Modal>
}
