"use client";
/* eslint-disable react/no-children-prop */

import Link from "next/link";
import { useRouter, useSearchParams } from "next/navigation";
import { useState } from "react";
import { BookOpen, Check, CircleAlert, Clock3, MessageSquareText, TrendingUp, UsersRound } from "lucide-react";
import { CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import type { getParentAttendanceAnalytics, getParentHistoryAnalytics, getParentProgressAnalytics, getParentReviewsAnalytics, getParentTestsAnalytics, getParentWordsAnalytics } from "../lib/repositories/parent-pages.repository";

type Data<T extends (...args: never[]) => unknown> = Awaited<ReturnType<T>>;
const periodLabels:Record<string,string>={"3m":"Последние 3 месяца","6m":"Последние 6 месяцев",academic:"Текущий учебный год",all:"Весь период"};
const statusLabels:Record<string,string>={PRESENT:"Присутствовал",ABSENT:"Отсутствовал",LATE:"Опоздал",EXCUSED:"Уважительная причина",LESSON_CANCELLED:"Урок отменён",NEW:"Новое",LEARNING:"Изучает",NEEDS_REVIEW:"Нужно повторить",MASTERED:"Освоено",CONFIDENT:"Уверенно знает"};
const progressLabels:Record<string,string>={SIGNIFICANT:"Значительный прогресс",STABLE:"Стабильный прогресс",SMALL:"Небольшой прогресс",NO_VISIBLE_CHANGE:"Без заметных изменений",NEEDS_ATTENTION:"Требуется дополнительное внимание"};
const colors=["#e73848","#1b78d0","#24a46d","#f59e0b","#8b5cf6","#0ea5a8"];
const date=(value:string|null)=>value?new Intl.DateTimeFormat("ru-RU",{day:"2-digit",month:"short",year:"numeric",timeZone:"Asia/Aqtau"}).format(new Date(value)):"—";
const monthName=(month:number,year:number)=>new Intl.DateTimeFormat("ru-RU",{month:"long",year:"numeric",timeZone:"UTC"}).format(new Date(Date.UTC(year,month-1,1)));
const display=(value:number|null|undefined,suffix="")=>value==null?"—":`${value}${suffix}`;

function ChildPeriodNav({children,selected,path,period}:{children:Array<{id:string;name:string}>;selected:string;path:string;period:string}){
  const router=useRouter(),params=useSearchParams();
  function changePeriod(value:string){const next=new URLSearchParams(params.toString());next.set("period",value);router.push(`${path}?${next.toString()}`)}
  return <div className="analytics-context"><div className="child-switcher">{children.map(child=><Link className={child.id===selected?"active":""} href={`${path}?child=${child.id}&period=${period}`} key={child.id}>{child.name}</Link>)}</div><label className="period-selector"><span>Период</span><select value={period} onChange={event=>changePeriod(event.target.value)}>{Object.entries(periodLabels).map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></label></div>;
}

function Empty({title,text}:{title:string;text:string}){return <section className="section-card empty-state"><span><CircleAlert/></span><h3>{title}</h3><p>{text}</p></section>}
function Badge({value}:{value:string}){return <span className={`badge analytics-badge status-${value.toLowerCase()}`}>{statusLabels[value]??value}</span>}

function TrendChart({data,lines,yDomain=[0,100],empty}:{data:Array<Record<string,unknown>>;lines:Array<{key:string;name:string;color:string}>;yDomain?:[number|"auto",number|"auto"];empty:string}){
  if(!data.length)return <div className="chart-empty"><TrendingUp/><p>{empty}</p></div>;
  return <div className="chart-scroll"><div className="chart-canvas"><ResponsiveContainer width="100%" height={280}><LineChart data={data} margin={{top:12,right:18,left:-12,bottom:4}}><CartesianGrid strokeDasharray="3 3" stroke="#eceef1"/><XAxis dataKey="label" tick={{fontSize:11}}/><YAxis domain={yDomain} tick={{fontSize:11}}/><Tooltip contentStyle={{borderRadius:12,border:"1px solid #eceef1"}} formatter={(value,name,item)=>{const row=item.payload as Record<string,unknown>;return row.score!==undefined?[`${value}% · ${row.score}/${row.maxScore} · ${row.date}`,String(row.title)]:[value,name]}}/>{lines.map(line=><Line type="monotone" dataKey={line.key} name={line.name} stroke={line.color} strokeWidth={3} dot={{r:4}} activeDot={{r:6}} connectNulls key={line.key}/>)}</LineChart></ResponsiveContainer></div></div>;
}

function SkillChart({skills}:{skills:NonNullable<Data<typeof getParentProgressAnalytics>["analytics"]>["skills"]}){
  const defaults=skills.categories.slice(0,4).map(item=>item.id),[selected,setSelected]=useState(defaults);
  const data=skills.points.map(point=>({label:point.label,...point.values}));
  function toggle(id:string){setSelected(current=>current.includes(id)?current.filter(item=>item!==id):current.length<4?[...current,id]:current)}
  return <><div className="skill-selector">{skills.categories.map((skill,index)=><button type="button" className={selected.includes(skill.id)?"active":""} onClick={()=>toggle(skill.id)} key={skill.id}><i style={{background:colors[index%colors.length]}}/>{skill.name}</button>)}</div><TrendChart data={data} lines={skills.categories.filter(skill=>selected.includes(skill.id)).map((skill,index)=>({key:skill.id,name:skill.name,color:colors[index%colors.length]}))} yDomain={[1,10]} empty="Учитель пока не опубликовал ежемесячные оценки"/></>;
}

export function ParentProgressAnalyticsPage({data}:{data:Data<typeof getParentProgressAnalytics>}){
  if(!data.child)return <Empty title="К аккаунту пока не привязан ребёнок" text="Обратитесь к администратору учебного центра."/>;const analytics=data.analytics!;
  const testData=analytics.tests.map(item=>({label:item.title,percentage:item.percentage,score:item.score,maxScore:item.maxScore,date:date(item.date)})),attendanceData=analytics.attendance.trend.map(item=>({label:item.label,percent:item.percent})),wordData=analytics.vocabulary.trend.map(item=>({label:item.label,count:item.count}));
  return <div className="parent-analytics-page"><ChildPeriodNav children={data.children} selected={data.child.id} path="/parent/progress" period={data.period}/><div className="analytics-kpis"><article><span>Средняя оценка навыков</span><strong>{display(analytics.kpis.skillAverage," / 10")}</strong></article><article><span>Средний результат тестов</span><strong>{display(analytics.kpis.testAverage,"%")}</strong></article><article><span>Посещаемость</span><strong>{display(analytics.kpis.attendancePercent,"%")}</strong></article><article><span>Освоено слов</span><strong>{analytics.kpis.masteredWords}</strong></article></div><section className="section-card analytics-chart-card"><div className="section-head"><div><h2>Развитие навыков</h2><p>Только опубликованные оценки по месяцам</p></div></div><SkillChart skills={analytics.skills}/></section><div className="skill-current-grid">{analytics.skills.current.map(item=><article className="section-card" key={item.id}><span>{item.name}</span><strong>{display(item.score," / 10")}</strong><small className={item.change&&item.change>0?"positive":"neutral"}>{item.change==null?"Нет предыдущего месяца":item.change>0?`↑ +${item.change} к прошлому месяцу`:item.change===0?"→ Без изменений":`Изменение ${item.change}`}</small></article>)}</div><div className="analytics-chart-grid"><section className="section-card analytics-chart-card"><div className="section-head"><h2>Тесты в динамике</h2></div><TrendChart data={testData} lines={[{key:"percentage",name:"Результат, %",color:colors[1]}]} empty="Результатов тестов пока нет"/></section><section className="section-card analytics-chart-card"><div className="section-head"><h2>Посещаемость по месяцам</h2></div><TrendChart data={attendanceData} lines={[{key:"percent",name:"Посещаемость, %",color:colors[2]}]} empty="Недостаточно данных о посещаемости"/></section><section className="section-card analytics-chart-card"><div className="section-head"><h2>Освоено слов по месяцам</h2></div><TrendChart data={wordData} lines={[{key:"count",name:"Освоено слов",color:colors[4]}]} yDomain={[0,"auto"]} empty="Динамика словарного запаса пока не сформирована"/></section></div>{data.report?<MonthlyReport report={data.report}/>:<Empty title="Месячный отчёт пока недоступен" text="Он появится после публикации ежемесячных оценок."/>}</div>;
}

function MonthlyReport({report}:{report:NonNullable<Data<typeof getParentProgressAnalytics>["report"]>}){
  return <section className="section-card monthly-report"><div className="section-head"><div><span className="eyebrow">Сводный месячный отчёт</span><h2>{monthName(report.month,report.year)}</h2><p>{report.student} · {report.group} · {report.teacher}</p></div></div><div className="report-metrics"><div><span>Посещаемость</span><strong>{report.attendance.attended} из {report.attendance.lessons}</strong><small>{display(report.attendance.percent,"%")}</small></div><div><span>Пройдено тем</span><strong>{report.topics}</strong><small>{report.lessons} занятий</small></div><div><span>Изучено слов</span><strong>{report.newWords}</strong><small>{report.masteredWords} освоено</small></div><div><span>Домашние задания</span><strong>{report.homework.completed} из {report.homework.total}</strong><small>выполнено</small></div><div><span>Средний тест</span><strong>{display(report.testAverage,"%")}</strong></div></div><div className="report-skills">{report.skills.map(skill=><div key={skill.name}><span>{skill.name}</span><strong>{skill.score} / 10</strong></div>)}</div>{report.review&&<div className="report-review"><MessageSquareText/><div><h3>Отзыв учителя</h3><p>{report.review.generalComment||report.review.achievements||"Отзыв опубликован"}</p>{report.review.recommendations&&<small>{report.review.recommendations}</small>}</div></div>}</section>;
}

export function ParentTestsAnalyticsPage({data}:{data:Data<typeof getParentTestsAnalytics>}){if(!data.child)return <Empty title="К аккаунту пока не привязан ребёнок" text="Обратитесь к администратору."/>;return <div className="parent-analytics-page"><ChildPeriodNav children={data.children} selected={data.child.id} path="/parent/tests" period={data.period}/>{!data.items.length?<Empty title="Результатов тестов пока нет" text="После завершения и проверки теста результат появится здесь."/>:<div className="test-result-grid">{data.items.map(item=><section className="section-card test-result-card" key={item.id}><div className="section-head"><div><span className="eyebrow">{item.unit}</span><h2>{item.title}</h2><p>{date(item.date)}</p></div><strong className="test-percent">{display(item.percentage,"%")}</strong></div><div className="score-ratio"><b>{item.score}</b><span>из {item.maxScore}</span></div>{item.teacherComment&&<blockquote>{item.teacherComment}</blockquote>}{item.skillScores.length>0&&<div className="bar-list">{item.skillScores.map(score=><div key={score.name}><span>{score.name}</span><i><b style={{width:`${score.percentage??0}%`}}/></i><strong>{score.score} / {score.maxScore}</strong></div>)}</div>}</section>)}</div>}</div>}

export function ParentAttendanceAnalyticsPage({data}:{data:Data<typeof getParentAttendanceAnalytics>}){if(!data.child)return <Empty title="К аккаунту пока не привязан ребёнок" text="Обратитесь к администратору."/>;const analytics=data.analytics!;return <div className="parent-analytics-page"><ChildPeriodNav children={data.children} selected={data.child.id} path="/parent/attendance" period={data.period}/><div className="analytics-kpis attendance-kpis"><article><span>Посещаемость</span><strong>{display(analytics.summary.percent,"%")}</strong></article><article><span>Проведено занятий</span><strong>{analytics.summary.lessons}</strong></article><article><span>Присутствовал</span><strong>{analytics.summary.present}</strong></article><article><span>Отсутствовал</span><strong>{analytics.summary.absent}</strong></article><article><span>Опоздал</span><strong>{analytics.summary.late}</strong></article><article><span>Уважительная причина</span><strong>{analytics.summary.excused}</strong></article></div><section className="section-card"><div className="section-head"><div><h2>Календарь посещаемости</h2><p>Отменённые уроки не влияют на процент</p></div></div><div className="attendance-legend">{["PRESENT","ABSENT","LATE","EXCUSED","LESSON_CANCELLED"].map(value=><Badge value={value} key={value}/>)}</div>{analytics.items.length?<div className="attendance-calendar">{analytics.items.map(item=><article className={`calendar-day status-${item.status.toLowerCase()}`} key={item.id}><time>{date(item.lessonDate)}</time><strong>{item.topic}</strong><Badge value={item.status}/>{item.comment&&<small>{item.comment}</small>}</article>)}</div>:<p className="muted">За выбранный период данных нет.</p>}</section></div>}

export function ParentWordsAnalyticsPage({data,filters}:{data:Data<typeof getParentWordsAnalytics>;filters:{book?:string;unit?:string;status?:string;q?:string}}){if(!data.child)return <Empty title="К аккаунту пока не привязан ребёнок" text="Обратитесь к администратору."/>;return <div className="parent-analytics-page"><ChildPeriodNav children={data.children} selected={data.child.id} path="/parent/words" period={data.period}/><div className="analytics-kpis"><article><span>Всего слов</span><strong>{data.summary?.summary.total??0}</strong></article><article><span>Освоено</span><strong>{data.summary?.summary.masteredTotal??0}</strong></article><article><span>Нужно повторить</span><strong>{data.summary?.summary.needsReview??0}</strong></article><article><span>Изучает</span><strong>{data.summary?.summary.learning??0}</strong></article></div><form className="section-card word-filter-form"><input type="hidden" name="child" value={data.child.id}/><input type="hidden" name="period" value={data.period}/><label><span>Поиск</span><input name="q" defaultValue={filters.q} placeholder="Слово или перевод"/></label><label><span>Учебник</span><select name="book" defaultValue={filters.book}><option value="">Все учебники</option>{data.filterOptions.books.map(book=><option value={book.id} key={book.id}>{book.name}</option>)}</select></label><label><span>Unit</span><select name="unit" defaultValue={filters.unit}><option value="">Все разделы</option>{data.filterOptions.units.filter(unit=>!filters.book||unit.bookId===filters.book).map(unit=><option value={unit.id} key={unit.id}>{unit.name}</option>)}</select></label><label><span>Статус</span><select name="status" defaultValue={filters.status}><option value="">Все статусы</option>{["NEW","LEARNING","NEEDS_REVIEW","MASTERED","CONFIDENT"].map(value=><option value={value} key={value}>{statusLabels[value]}</option>)}</select></label><button className="btn">Применить</button></form>{!data.words.length?<Empty title="Слова ещё не добавлены" text="Изученные слова появятся после занятий."/>:<section className="section-card"><div className="vocabulary-table analytics-vocabulary">{data.words.map(item=><div key={item.word.id}><div><b>{item.word.english}</b><span>{item.word.translation}</span></div><span>{item.word.topic.unit.book.name}</span><span>{item.word.topic.unit.name}</span><span>{item.word.topic.name}</span><Badge value={item.status}/></div>)}</div></section>}</div>}

export function ParentReviewsAnalyticsPage({data}:{data:Data<typeof getParentReviewsAnalytics>}){if(!data.child)return <Empty title="К аккаунту пока не привязан ребёнок" text="Обратитесь к администратору."/>;return <div className="parent-analytics-page"><ChildPeriodNav children={data.children} selected={data.child.id} path="/parent/reviews" period={data.period}/>{!data.items.length?<Empty title="Отзыв учителя за выбранный период пока не опубликован" text="Черновики недоступны в кабинете родителя."/>:<div className="feedback-list">{data.items.map(item=><section className="section-card review-card" key={item.id}><div className="section-head"><div><span className="eyebrow">{monthName(item.month,item.year)}</span><h2>{item.teacher.name}</h2></div><span className="badge green">{progressLabels[item.progressLevel]}</span></div><div className="review-sections"><div><h3>Достижения</h3><p>{item.achievements||"—"}</p></div><div><h3>Что улучшить</h3><p>{item.improvements||"—"}</p></div><div><h3>Рекомендации</h3><p>{item.recommendations||"—"}</p></div><div><h3>Общий комментарий</h3><p>{item.generalComment||"—"}</p></div></div></section>)}</div>}</div>}

export function ParentHistoryAnalyticsPage({data}:{data:Data<typeof getParentHistoryAnalytics>}){if(!data.child)return <Empty title="К аккаунту пока не привязан ребёнок" text="Обратитесь к администратору."/>;const history=data.history!;return <div className="parent-analytics-page"><ChildPeriodNav children={data.children} selected={data.child.id} path="/parent/history" period={data.period}/><div className="history-summary-grid"><section className="section-card"><div className="section-head"><h2>История групп</h2><UsersRound/></div>{history.groups.map(group=><div className="history-period" key={group.id}><strong>{group.name}</strong><span>{date(group.startedAt)} — {group.endedAt?date(group.endedAt):"сейчас"}</span><small>{group.level} · {group.book}</small></div>)}</section><section className="section-card"><div className="section-head"><h2>История преподавателей</h2><BookOpen/></div>{history.teachers.map((teacher,index)=><div className="history-period" key={`${teacher.name}-${index}`}><strong>{teacher.name}</strong><span>{date(teacher.startedAt)} — {teacher.endedAt?date(teacher.endedAt):"сейчас"}</span><small>{teacher.group}</small></div>)}</section></div><section className="section-card"><div className="section-head"><h2>История обучения</h2><Clock3/></div>{history.events.length?<div className="timeline analytics-timeline">{history.events.map(item=><div key={item.id}><i><Check/></i><time>{date(item.eventDate)}</time><h3>{item.title}</h3><p>{item.description||[item.group?.name,item.teacher?.name,item.book?.name,item.unit?.name].filter(Boolean).join(" · ")}</p></div>)}</div>:<p className="muted">За выбранный период событий пока нет.</p>}</section></div>}
