"use client";

import Link from "next/link";
import { usePathname } from "next/navigation";
import { signOut } from "next-auth/react";
import { useState } from "react";
import { BarChart3, BookOpen, CalendarDays, ClipboardCheck, FileText, GraduationCap, History, Home, LogOut, Menu, MessageSquareText, Star, UserRound, UsersRound, X } from "lucide-react";

const icons={home:Home,groups:UsersRound,attendance:CalendarDays,lessons:BookOpen,topics:BookOpen,homework:ClipboardCheck,words:GraduationCap,tests:FileText,assessments:Star,reviews:MessageSquareText,students:UsersRound,profile:UserRound,progress:BarChart3,history:History};
const teacherNav=[["Главная","/teacher","home"],["Мои группы","/teacher/groups","groups"],["Посещаемость","/teacher/attendance","attendance"],["Уроки и темы","/teacher/lessons","lessons"],["Домашние задания","/teacher/homework","homework"],["Слова","/teacher/words","words"],["Тесты","/teacher/tests","tests"],["Ежемесячные оценки","/teacher/assessments","assessments"],["Отзывы","/teacher/reviews","reviews"],["Ученики","/teacher/students","students"],["Профиль","/teacher/profile","profile"]] as const;
const parentNav=[["Главная","/parent","home"],["Темы и уроки","/parent/topics","topics"],["Слова","/parent/words","words"],["Домашние задания","/parent/homework","homework"],["Посещаемость","/parent/attendance","attendance"],["Тесты","/parent/tests","tests"],["Прогресс","/parent/progress","progress"],["Отзывы","/parent/reviews","reviews"],["История обучения","/parent/history","history"],["Профиль","/parent/profile","profile"]] as const;
const titles:Record<string,string>={teacher:"Кабинет учителя",parent:"Кабинет родителя",groups:"Мои группы",attendance:"Посещаемость",lessons:"Уроки и темы",topics:"Темы и уроки",homework:"Домашние задания",words:"Словарь",tests:"Тесты",assessments:"Ежемесячные оценки",reviews:"Отзывы",students:"Ученики",profile:"Профиль",progress:"Прогресс",history:"История обучения"};

export function RoleShell({role,user,children}:{role:"teacher"|"parent";user:{name:string;email:string};children:React.ReactNode}){
  const pathname=usePathname(),nav=role==="teacher"?teacherNav:parentNav,[drawer,setDrawer]=useState(false);const first=pathname.split("/").filter(Boolean)[1];const title=titles[first??role]??"Happy Town";
  const links=<nav>{nav.map(([label,href,key])=>{const Icon=icons[key];const active=href===`/${role}`?pathname===href:pathname.startsWith(href);return <Link className={active?"active":""} href={href} key={href} onClick={()=>setDrawer(false)}><Icon size={18}/>{label}</Link>})}</nav>;
  return <div className="app-shell role-layout"><aside className="sidebar"><Link className="brand role-brand" href={`/${role}`}>Happy Town</Link>{links}<button className="shell-logout" onClick={()=>signOut({callbackUrl:"/login"})}><LogOut size={17}/>Выйти</button></aside><div className={`mobile-drawer ${drawer?"open":""}`}><button onClick={()=>setDrawer(false)} aria-label="Закрыть меню"><X/></button><Link className="brand role-brand" href={`/${role}`}>Happy Town</Link>{links}</div>{drawer&&<button className="drawer-backdrop" onClick={()=>setDrawer(false)} aria-label="Закрыть меню"/>}<main><header className="topbar"><button className="icon-btn menu-trigger" onClick={()=>setDrawer(true)} aria-label="Открыть меню"><Menu/></button><div><p className="eyebrow">Happy Town</p><h1>{title}</h1></div><div className="profile-chip"><span className="avatar">{user.name.split(" ").map(item=>item[0]).slice(0,2).join("")}</span><div><b>{user.name}</b><small>{user.email}</small></div></div></header><div className="content">{children}</div></main><nav className="mobile-nav">{nav.slice(0,4).map(([label,href,key])=>{const Icon=icons[key];return <Link href={href} className={(href===`/${role}`?pathname===href:pathname.startsWith(href))?"active":""} key={href}><Icon size={19}/><span>{label}</span></Link>})}<button onClick={()=>setDrawer(true)}><Menu size={19}/><span>Ещё</span></button></nav></div>;
}
