"use client";

import { useState } from "react";
import { Archive, Loader2, Pencil, Send, X } from "lucide-react";
import { useRouter } from "next/navigation";

type Kind="lesson"|"homework"|"word"|"test"|"assessment"|"review";
type Item={id:string;title:string;subtitle?:string;status?:string;secondary?:string};
const config:Record<Kind,{update?:string;archive?:string;publish?:string;idKey:string}>={lesson:{update:"updateLesson",archive:"archiveLesson",idKey:"lessonId"},homework:{update:"updateHomework",archive:"archiveHomework",idKey:"homeworkId"},word:{update:"updateWord",archive:"archiveWord",idKey:"wordId"},test:{update:"updateTest",archive:"archiveTest",idKey:"testId"},assessment:{publish:"publishMonthlyAssessment",idKey:"assessmentId"},review:{publish:"publishTeacherReview",idKey:"reviewId"}};

export function TeacherRecordActions({kind,items}:{kind:Kind;items:Item[]}){
  const router=useRouter(),[editing,setEditing]=useState<string|null>(null),[busy,setBusy]=useState<string|null>(null),[message,setMessage]=useState("");
  async function act(action:string,item:Item,extra:Record<string,unknown>={}){if(action.startsWith("archive")&&!confirm(`Переместить «${item.title}» в архив?`))return;setBusy(item.id);setMessage("");try{const idKey=config[kind].idKey,response=await fetch("/api/teacher/actions",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action,data:{[idKey]:item.id,...extra}})}),result=await response.json();if(!response.ok)throw new Error(result.error||"Не удалось выполнить действие");setEditing(null);setMessage(action.startsWith("publish")?"Опубликовано":"Изменения сохранены");router.refresh()}catch(error){setMessage(error instanceof Error?error.message:"Не удалось выполнить действие")}finally{setBusy(null)}}
  if(!items.length)return null;
  return <section className="section-card record-management"><div className="section-head"><div><h2>Управление</h2><p className="muted">Изменение статуса и содержания записей</p></div>{message&&<span className="success-text">{message}</span>}</div>{items.map(item=><div className="record-action-row" key={item.id}>{editing===item.id?<EditForm kind={kind} item={item} busy={busy===item.id} onCancel={()=>setEditing(null)} onSave={extra=>act(config[kind].update!,item,extra)}/>:<><div><b>{item.title}</b>{item.subtitle&&<small>{item.subtitle}</small>}</div><div className="row-actions">{config[kind].update&&<button className="btn secondary small" onClick={()=>setEditing(item.id)}><Pencil size={15}/>Изменить</button>}{config[kind].publish&&item.status!=="PUBLISHED"&&<button className="btn small" disabled={busy===item.id} onClick={()=>act(config[kind].publish!,item)}>{busy===item.id?<Loader2 className="spin"/>:<Send size={15}/>}Опубликовать</button>}{config[kind].archive&&<button className="btn danger small" disabled={busy===item.id} onClick={()=>act(config[kind].archive!,item)}>{busy===item.id?<Loader2 className="spin"/>:<Archive size={15}/>}В архив</button>}</div></>}</div>)}</section>;
}

function EditForm({kind,item,busy,onCancel,onSave}:{kind:Kind;item:Item;busy:boolean;onCancel:()=>void;onSave:(data:Record<string,unknown>)=>void}){const [title,setTitle]=useState(item.title),[secondary,setSecondary]=useState(item.secondary??"");return <form className="record-edit" onSubmit={event=>{event.preventDefault();onSave(kind==="word"?{english:title,translation:secondary}:{title})}}><label><span>{kind==="word"?"Слово":"Название"}</span><input value={title} onChange={event=>setTitle(event.target.value)} required/></label>{kind==="word"&&<label><span>Перевод</span><input value={secondary} onChange={event=>setSecondary(event.target.value)} required/></label>}<button className="btn small" disabled={busy}>{busy?<Loader2 className="spin"/>:"Сохранить"}</button><button className="icon-button" type="button" onClick={onCancel} aria-label="Отменить"><X/></button></form>}
